//! Data structures for (de-)serialization as generated by `prost-build`.

// Generated by [`prost-build`]
include!(concat!(env!("OUT_DIR"), "/mehari.server.rs"));
// Generated by [`pbjson-build`]
include!(concat!(env!("OUT_DIR"), "/mehari.server.serde.rs"));
