name: add needs-review pull requests to projects

on:
  pull_request:
    types:
      - labeled

jobs:
  add-to-project:
    name: Add pull request to project
    runs-on: ubuntu-latest
    steps:
      - name: register pull requests with release planning project
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/varfish-org/projects/2
          github-token: ${{ secrets.BOT_TOKEN }}
          labeled: needs-review
