name: GitHub Pages Build And Deploy

on:
  schedule:
    - cron: '0 18 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    defaults:
      run:
        shell: bash -el {0}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          lfs: true

      - name: locosopa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: koesterlab/locosopa@54e01e5b0f4e4163c99264cb0739f77ee40c71b8 # v1.1.2
        with:
          config: page/config.yaml
          path: build
