name: GitHub Pages Build And Deploy

on:
  schedule:
    - cron: '0 18 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    defaults:
      run:
        shell: bash -el {0}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          lfs: true

      - name: locosopa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: koesterlab/locosopa@92c786b2bb21f57e14d5c3ba1db8e7d5234bf39e # v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: page/config.yaml
          path: build
